apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp  # Matches the label in deployment.yaml
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}          # External port exposed by the Service
      targetPort: {{ .Values.service.targetPort | default 3000 }}  # Internal port where the Node.js app listens
  type: {{ .Values.service.type }}    # Choose LoadBalancer for external access (use NodePort for local clusters)
